### ISSUE TITLE
Add YouTube link and icon to the contact us footer

### ISSUE THREAD

**Issue by mrunankpawar** [Hack-Club-TechBrewers/Hack-Club-TechBrewers.github.io#44]
While working on this issue keep the following things in mind:
- Make sure to add the correct channel link (https://www.youtube.com/channel/UCs8zpk8H6Vhtby5NGL11EeQ)
- Use of icon should be similar to other social icons.

**Comment by mrunankpawar** [comment]
Make this change to the footer of all the pages

**Comment by pabitra0011** [comment]
Ok I will make this change to the footer of all pages.
