### ISSUE TITLE
Update the mail link of website

### ISSUE THREAD

**Issue by mrunankpawar** [Hack-Club-TechBrewers/Hack-Club-TechBrewers.github.io#46]
There is a minor update that needs to be done by adding **_mailto:_** to the email in the contact us part.

**Comment by pabitra0011** [comment]
@mrunankpawar  Can you assigned me to solve this minor issue.

**Comment by mrunankpawar** [comment]
> @mrunankpawar Can you assigned me to solve this minor issue.

Thank you for your contribution!!
