### ISSUE TITLE
Change event in event page to flipping card

### ISSUE THREAD

**Issue by mrunankpawar** [Hack-Club-TechBrewers/Hack-Club-TechBrewers.github.io#63]
We can convert the cards on the event page to flipping card as whenever a person checks out the website, they are just able to see the poster and when they click on the poster card will flip and contains the information about the event and link to the event.

**Comment by ena-04** [comment]
i would like to work on this issue. can you please assign it to me?

**Comment by mrunankpawar** [comment]
Hey sure, have assigned the issue to you. While creating a PR just make sure to include images or videos of the changes you have made.

Thank you!

**Comment by ena-04** [comment]
@mrunankpawar does it look fine?

https://user-images.githubusercontent.com/89613867/196001131-334c92cd-97a0-443b-bf46-ea56a6b1300c.mp4

**Comment by mrunankpawar** [comment]
> @mrunankpawar does it look fine?
> 
>  flip-card.mp4

Wow, that's awesome !! Great work @ena-04

**Comment by ena-04** [comment]
if i work on 2 different issues, how do i make it count as two separate prs?
