### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by ena-04** [Hack-Club-TechBrewers/Hack-Club-TechBrewers.github.io#65]
hey, i would like to work on this

**Comment by mrunankpawar** [comment]
Hey, thanks for raising the issue, we would be more than happy to add dark mode to the community website.

Looking forward to your PR solving this issue. Just make sure to add screenshots of the changes you have made.

Thank you!

**Comment by ena-04** [comment]
@mrunankpawar here are the snaps of the changes that i've made. i've also raised a pr, please check.
![Screenshot (168)](https://user-images.githubusercontent.com/89613867/195996935-b33fe4b2-6886-4752-9efd-9131b40e4053.png)
![Screenshot (169)](https://user-images.githubusercontent.com/89613867/195996939-81b92f2a-799f-4648-93a4-eecb7d6e265d.png)
![Screenshot (170)](https://user-images.githubusercontent.com/89613867/195996941-6518a0e7-0974-451b-a512-965639a87670.png)
![Screenshot (165)](https://user-images.githubusercontent.com/89613867/195996943-8f5771f2-f39f-47a3-96ff-1aa10726abae.png)

**Comment by ena-04** [comment]
also please do add the hacktoberfest label to this issue

**Comment by mrunankpawar** [comment]
> 

Can you convert it into a more of darker shade, also can you change the logo on the navbar to this when in dark mode (https://github.com/Hack-Club-TechBrewers/Hack-Club-TechBrewers.github.io/blob/main/images/Logos/TechBrewersLogo.png)?

**Comment by mrunankpawar** [comment]
> also please do add the hacktoberfest label to this issue

Will be adding the hacktoberfest-accepted label to the PR associated with the issue

**Comment by ena-04** [comment]
> > 
> 
> @ena-04 Can you convert it into a more of darker shade, also can you change the logo on the navbar to this when in dark mode (https://github.com/Hack-Club-TechBrewers/Hack-Club-TechBrewers.github.io/blob/main/images/Logos/TechBrewersLogo.png)?

okay sure

**Comment by ena-04** [comment]
@mrunankpawar is it better now?
![Screenshot (171)](https://user-images.githubusercontent.com/89613867/196002530-b921df61-4bff-4b51-8355-ce291907b01c.png)
![Screenshot (172)](https://user-images.githubusercontent.com/89613867/196002535-1b1f510e-2f02-4ad3-808c-c60c9ed281c8.png)
